### ISSUE TITLE
CI Hangs forever

### ISSUE THREAD

**Issue by AlexShemeshWix** [wixplosives/stylable-intelligence#72]
Both Jenkins and Travis are hang forever when they are running npm run test command.
Jenkins:
https://cijoe.wixcore3.com/job/build-generic/897/console
Travis
https://travis-ci.org/wixplosives/stylable-intelligence/builds/274689101?utm_source=github_status&utm_medium=notification

Ive isolated issue on Jenkins agent.
internal-jenkins-slave3a.core-3.wixcore3.com

I can see vscode process running  in background when test hangs

ps aux | grep vscode output 

```
ubuntu   21536  0.0  0.0  12944  1028 pts/2    S+   07:36   0:00 grep vscode
ubuntu@internal-jenkins-slave3a:~$ ps aux | grep vscode
ubuntu   21648  2.9  0.9 1082840 74804 pts/1   Sl+  07:36   0:00 /home/jenkins-slave/workspace/build-generic/packages/client/.vscode-test/VSCode-linux-x64/code --extensionDevelopmentPath=/home/jenkins-slave/workspace/build-generic/packages/client --extensionTestsPath=/home/jenkins-slave/workspace/build-generic/packages/client/dist/test /home/jenkins-slave/workspace/build-generic/packages/client/test/cases
ubuntu   21650  0.0  0.3 330832 28544 pts/1    S+   07:36   0:00 /home/jenkins-slave/workspace/build-generic/packages/client/.vscode-test/VSCode-linux-x64/code --type=zygote --no-sandbox
ubuntu   21676  0.5  0.7 478500 55220 pts/1    Sl+  07:36   0:00 /home/jenkins-slave/workspace/build-generic/packages/client/.vscode-test/VSCode-linux-x64/code --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,23,74 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x0000 --gpu-device-id=0x0000 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --service-request-channel-token=084DCB1699055152DF6670A30EAEBF3D
```

if i  kill all vscode processes and run  
`/home/jenkins-slave/workspace/build-generic/packages/client/.vscode-test/VSCode-linux-x64/code
`

it will hang with following message 
```

{ errorCode: 'load',d-generic/packages/client/.vscode-test/VSCode-linux-x64/code
  moduleId: 'keytar',
  neededBy: [ 'vs/platform/credentials/node/credentialsService' ],
  detail:
   Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
       at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
       at Object.Module._extensions..node (module.js:598:18)
       at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       at n (/home/jenkins-slave/workspace/build-generic/packages/client/.vscode-test/VSCode-linux-x64/resources/app/out/vs/loader.js:4:10954)
       at Object.<anonymous> (/home/jenkins-slave/workspace/build-generic/packages/client/.vscode-test/VSCode-linux-x64/resources/app/node_modules/keytar/lib/keytar.js:1:169)
       at Object.<anonymous> (/home/jenkins-slave/workspace/build-generic/packages/client/.vscode-test/VSCode-linux-x64/resources/app/node_modules/keytar/lib/keytar.js:55:3) }
```

When i run tests **locally** on my machine i can see error message like this

```
Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

So my guess it has some problem with certificate and it causes VScode to crash and not exit in CI environment.

**Comment by AlexShemeshWix** [comment]
This is our bug.
https://github.com/Microsoft/vscode/issues/33998
Fix applied. All works now.
